version: "3.9"

services:
  frontend:
    build:
      context: ./iot_data
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Expose frontend on port 5173
    volumes:
      - ./iot_data:/app
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"] # Ensure the correct command is used

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Expose backend on port 8000
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db_host/db_name # Ensure DATABASE_URL is set correctly
