version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-iot
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iot_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-net

  fastapi:
    build: .
    container_name: fastapi-iot
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - iot-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  iot-net:
